name: Build and Push TraceabilityDriver Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "TraceabilityDriver/**"
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.DOCKERHUB_REGISTRY }}
  IMAGE_NAME: traceability-driver

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push amd64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./TraceabilityDriver/Dockerfile
        push: true
        platforms: linux/amd64
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
